name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  stage:
    name: "Build Dist"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Prepare git and repo"
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout staging
        git merge "${GITHUB_REF#refs/heads/}" 
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn build
    - run: yarn package
    - name: "Pushing new build"
      run: |
        git add -f dist/
        git diff-index --quiet HEAD || git commit -m "Build dist"
        git push

# Check `git diff-index --quiet HEAD` first, then to commit only if necessary
# Ref: https://stackoverflow.com/a/8123841/5488616
